# Generated by Django 5.2.6 on 2025-11-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(choices=[('cloth', 'cloth'), ('googles', 'googles'), ('watch', 'watch')], max_length=20)),
                ('pcompany', models.CharField(choices=[('nike', 'nike'), ('puma', 'puma'), ('rolex', 'rolex')], max_length=30)),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('pdesc', models.TextField()),
                ('pimage', models.ImageField(default='', upload_to='product/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
