# Generated by Django 5.2.6 on 2025-11-27 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_whishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 17, 27, 45, 885812, tzinfo=datetime.timezone.utc)),
        ),
    ]
