# Generated by Django 5.2.6 on 2025-11-27 17:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_whishlist_ttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 17, 28, 13, 928040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttime', models.DateTimeField(default=datetime.datetime(2025, 11, 27, 17, 28, 13, 928315, tzinfo=datetime.timezone.utc))),
                ('total', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('payment', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
