# Generated by Django 5.2.6 on 2025-12-15 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_whishlist_ttime_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 15, 10, 41, 5, 869156, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='whishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 15, 10, 41, 5, 868898, tzinfo=datetime.timezone.utc)),
        ),
    ]
